In [6]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

import pickle

 Синтетические данные

In [7]:
bv=[-0.35,-0.31,-0.17,0.0,0.16,0.30,0.45,0.57,0.70,0.84,1.11,1.39,1.61,2.00]
k=[40000,28000,15500,10000,8500,7400,6600,6600,5400,4700,4000,3600,3000,2660]

In [8]:
print(len(bv))
print(len(k))

14
14


In [9]:
x=np.array(k).reshape(-1,1)
y=np.array(bv)

train_test_split

In [15]:
x_train,x_test,y_train,y_test=train_test_split(x, y,test_size=0.2,shuffle=True,random_state=42)

ML

In [17]:
#linear regression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)

In [18]:
y_pred

array([ 0.89455227,  0.97640785, -1.73226772])

In [19]:
x_test

array([[ 4700],
       [ 3600],
       [40000]])

cохраняем модель

In [20]:
pickle.dump(lr,open('lr_model.pkl','wb'))

In [21]:
model_load=pickle.load(open('lr_model.pkl','rb'))

In [22]:
model_load.predict(x_test)

array([ 0.89455227,  0.97640785, -1.73226772])